<?php
/**
 * Define the Book Outline Block/
 * Implementation of hook_block_info()
 */
function bookoblock_block_info() {
  $block['book_outline'] = array (
    'info' => 'Book Outline',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );  
  return $block;
}

/**
 * Define the contents and title of the block/
 * Implementation of hook_block_view()
 *
 * Returns a block array with the current book's outline as the body and te top
 * level book as the title if the page being viewd is a node and is part of a
 * book.
 *
 * Returns NULL if the current menu item is not part of a book heirarchy.
 */
function bookoblock_block_view() {
  if ($book = bookoblock_is_book_node()) {
    $max_depth = variable_get('bookoblock_depth', NULL);
    $max_depth = ($max_depth == 0) ? NULL : $max_depth; // menu_tree_all_data() doesn't accept zero for depth; convert zero to NULL
    $tree = menu_tree_all_data(book_menu_name($book['bid']), NULL, $max_depth);
    $book_name = (book_toc($book['bid'], 1));
    $block['subject'] = $book_name[$book['p1']];
    $block['content'] = menu_tree_output($tree);
    return $block;
  }
  // If the current node isn't part of a book, just return nothing.
  return NULL;
}

/**
 * Implementation of hook_block_configure
 *
 * Adds a depth select list on the block configuration page.
 */
function bookoblock_block_configure() {
  $form['bookoblock_depth'] = array(
    '#type' => 'select',
    '#options' => drupal_map_assoc(array(0,1,2,3,4,5,6,7,8,9)),
    '#title' => t('Book Outline Block Depth'),
    '#description' => t('Select the maximum depth of the Book Outline Block. Select "0" for no limit.'),
    '#default_value' => variable_get('bookoblock_depth', 0),
  );
  return $form;
}

/**
 * Implementation of hook_block_save
 *
 * Saves the depth value for the block.
 */
function bookoblock_block_save($delta = '', $edit = array()) {
  variable_set('bookoblock_depth', $edit['bookoblock_depth']);
}

/**
 * Checks to see if current node is part of a book.
 * Returns book array if it is part of a book, FALSE is not.
 */
function bookoblock_is_book_node() {
  if ((arg(0) == 'node') && (is_numeric(arg(1)))) {
    $node = menu_get_object();
    if (isset($node->book)) {
      return $node->book;
    }
  }
  return FALSE;
}

